package com.mycompany.guardarp_final;
// Generated 04-jun-2018 13:59:45 by Hibernate Tools 4.3.1



/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private String descripcion;
     private String password;

    public Cuentas() {
    }

    public Cuentas(String descripcion, String password) {
       this.descripcion = descripcion;
       this.password = password;
    }
   
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


